version: '3'

services:
  postgres:
      image: postgres:16.0
      container_name: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: secret
      ports:
        - 5432:5432
  keycloak:
      image: quay.io/keycloak/keycloak:22.0.5
      container_name: keycloak
      hostname: keycloak
      command: ["start-dev"]
      environment:
        KC_DB_URL: jdbc:postgresql://postgres/keycloak
        KC_DB: postgres
        KC_DB_USERNAME: postgres
        KC_DB_PASSWORD: secret
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 8080:8080
      depends_on:
        - postgres
volumes:
  postgres_data:
